version: '3.8'

services:

    frontend:
      build: ./example-frontend
      container_name: frontend
      ports:
        - 5000:5000

    backend:
      build: ./example-backend
      container_name: backend
      environment:
        - REDIS_HOST=redis
        - POSTGRES_HOST=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DATABASE=postgres
      ports:
        - 8080:8080
      depends_on:
        - redis
    redis:
      image: redis:latest
      container_name: redis
    postgres:
      image: postgres:13.2-alpine
      restart: unless-stopped
      environment:
        - POSTGRES_PASSWORD=postgres
      container_name: postgres
      volumes:
      - ./db-data:/var/lib/postgresql/data
