version: '3.8'

services:

    frontend:
      build: ./example-frontend
      container_name: frontend
      ports:
        - 5000:5000

    backend:
      build: ./example-backend
      container_name: backend
      environment:
        - REDIS_HOST=redis
      ports:
        - 8080:8080
      depends_on:
        - redis
    redis:
      image: redis:latest
      container_name: redis
      